keys:
  - &dev_pazuzu age15y4k929zaj9fdg3vd40pa40tgvrgv9mn22xfummn5zxfmkcw5d0st6prjx
  - &server_corp age1kgwk20cc6t68kqj5nhem6swvx6k4e7zjx2xdwy382360h8tdyqrq0nn3gf
  - &server_test_corp age1lzzlx60f9ra4evdkn4l9px735mz7uxml5467ptzc4hg3t86gn9mq3ddsxy
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dev_pazuzu
      - *server_corp
      - *server_test_corp
  - path_regex: host/corp/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dev_pazuzu
      - *server_corp
  - path_regex: host/pazuzu/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dev_pazuzu
