keys:
  - &dev_corp age1fnkhk9rv7r8gh84vxnhvndk4fgh20qcj4hvnfhdpumcydl6m6vrse50lrz
  - &dev_macmini age1x704pjnueguchkl54ly8w4w26ltys5900v7xnl7w3zlgasus09jszz45t8
  - &dev_pazuzu age15y4k929zaj9fdg3vd40pa40tgvrgv9mn22xfummn5zxfmkcw5d0st6prjx
  - &server_corp age1ck44jqpuz3zlthquvuh7wsemrjrgfzhn462sk7rlfetwxpgy0uqs79xn2h
  - &server_nocix_amd_legacy_hexcore age1z87rm3qrrspv44nsg73ntn9zys5g498lry4t4cy6x9hffapug5cqfprntm
  - &server_test_corp age1t3ryfktuhr3cysf49m9q2n8fkjf9ajjjnhztxw9hz8paxgk4lpcq065jge
  - &server_sync_nidus age1j90h7hcp4fctr2xwj4zf9cxuelm43wkujvryc9hk6rzzc37rwdmss035w7
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dev_corp
      - *dev_macmini
      - *dev_pazuzu
      - *server_corp
      - *server_nocix_amd_legacy_hexcore
      - *server_test_corp
      - *server_sync_nidus
  - path_regex: host/corp/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dev_corp
      - *dev_macmini
      - *dev_pazuzu
      - *server_corp
  - path_regex: host/pazuzu/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *dev_macmini
      - *dev_pazuzu
