keys:
  - &pazuzu_local age15y4k929zaj9fdg3vd40pa40tgvrgv9mn22xfummn5zxfmkcw5d0st6prjx
creation_rules:
  - path_regex: secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *pazuzu_local
  - path_regex: host/pazuzu/secrets/[^/]+\.(yaml|json|env|ini)$
    key_groups:
    - age:
      - *pazuzu_local
