{
	imports = [
		./asterisk.nix
		./authentik.nix
		./authentik-backup.nix
		./base.nix
		./caddy.nix
		./cloud-init.nix
		./collabora.nix
		./cloudreve.nix
		./do-agent.nix
		./frps.nix
		./glitchtip
		./element-web.nix
		#./fieldseeker-sync.nix
		./fish.nix
		./label-studio.nix
		./librechat.nix
		./minio.nix
		./nidus-sync.nix
		./openssh.nix
		./podman.nix
		./restic
		./sillytavern.nix
		./static-websites.nix
		./sudo.nix
		./synapse.nix
		./timecardbot.nix
		./tmux.nix
		./twenty-crm.nix
		./vikunja.nix
	];
}
