# Do not modify this file!	It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.	Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
	imports =
		[ (modulesPath + "/installer/scan/not-detected.nix")
		];

	boot.initrd.availableKernelModules = [ "ahci" "ohci_pci" "ehci_pci" "xhci_pci" "sd_mod" ];
	boot.initrd.kernelModules = [ "dm-snapshot" ];
	boot.kernelModules = [ ];
	boot.extraModulePackages = [ ];


	/*
	> sudo lsblk -o NAME,UUID,MOUNTPOINT
	NAME          UUID                                   MOUNTPOINT
	sda
	└─sda1        3d53510d-47ec-4b72-81f0-46ca2d7612f2
	sdb
	├─sdb1
	├─sdb2        F635-99FA                              /boot
	└─sdb3        Vd4Zk5-lUto-KdM8-RTRw-zNqU-PvpM-Ik8fBB
	  └─pool-root 392ad825-c133-4bf1-97f4-bedc7dffcff4   /
	zram0         2c42e053-9c56-440d-84e7-e1dcc43ebae7   [SWAP]
	fileSystems = {
		Commented out after getting:
			error: The option `fileSystems."/".device' has conflicting definition values:
			- In `/nix/store/gic0d1i76vscycwnmjjfny1g7vq42cl9-source/module.nix': "/dev/pool/root"
			- In `/nix/store/1vmgswmnkfga5hnjlm5if86nd2j66a9s-source/host/nocix/amd-legacy-quadcore/hardware-configuration.nix': "/dev/disk/by-uuid/392ad825-c133-4bf1-97f4-bedc7dffcff4"
		Use `lib.mkForce value` or `lib.mkDefault value` to change the priority on any of these definitions.
		"/" = {
			device = "/dev/disk/by-uuid/392ad825-c133-4bf1-97f4-bedc7dffcff4";
			fsType = "ext4";
		};
		"/boot" = {
			device = "/dev/disk/by-uuid/F635-99FA";
			fsType = "vfat";
			options = [ "fmask=0022" "dmask=0022" ];
		};
		"/mnt/bigdisk" = {
			device = "3d53510d-47ec-4b72-81f0-46ca2d7612f2";
			fsType = "btrfs";
			neededForBoot = false;
			options = [ "noatime" ];
		};
	};
	*/

	# Enables DHCP on each ethernet and wireless interface. In case of scripted networking
	# (the default) this is the recommended approach. When using systemd-networkd it's
	# still possible to use this option, but it's recommended to use it in conjunction
	# with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
	networking.useDHCP = lib.mkDefault true;
	# networking.interfaces.enp3s0.useDHCP = lib.mkDefault true;
	# networking.interfaces.enp4s0.useDHCP = lib.mkDefault true;

	nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
	hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
